INSERT INTO COUNTRY_MASTER (COUNTRY_ID, COUNTRY_NAME) VALUES (91,'INDIA');
INSERT INTO COUNTRY_MASTER (COUNTRY_ID, COUNTRY_NAME) VALUES (1,'USA');

INSERT INTO STATE_MASTER (STATE_ID, STATE_NAME, COUNTRY_ID) VALUES (53,'UTTAR PRADESH',91);
INSERT INTO STATE_MASTER (STATE_ID, STATE_NAME, COUNTRY_ID) VALUES (04,'CHHATTISGARH',91);
INSERT INTO STATE_MASTER (STATE_ID, STATE_NAME, COUNTRY_ID) VALUES (22,'NEW JERSEY',1);
INSERT INTO STATE_MASTER (STATE_ID, STATE_NAME, COUNTRY_ID) VALUES (33,'OHIO',1);

INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (11,'GORAKHPUR',53);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (12,'LUCKNOW',53);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (13,'RAIPUR',04);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (14,'BILASPUR',04);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (15,'ATLANTIC CITY',22);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (16,'PRINCETON',22);
INSERT INTO CITY_MASTER (CITY_ID, CITY_NAME, STATE_ID) VALUES (17,'CLEVELAND',33);
INSERT INTO CITY_MASTER (CITY_ID,  CITY_NAME,STATE_ID) VALUES (18,'DUBLIN',33);